# Generated by Django 3.0.6 on 2020-09-20 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cepa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('precioventa', models.FloatField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm', models.IntegerField(blank=True, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vino.Bodega')),
                ('cepa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vino.Cepa')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vino.Reserva')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vino.Unidad')),
            ],
        ),
    ]
