# Generated by Django 3.0.6 on 2020-09-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
