# Generated by Django 3.0.6 on 2020-09-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vino', '0002_auto_20200920_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
