# Generated by Django 3.0.6 on 2020-09-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vino', '0003_auto_20200920_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='cepa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
