# Generated by Django 3.0.6 on 2020-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vino', '0004_cepa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='existencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vino',
            name='ultimacompra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
