# Generated by Django 3.0.6 on 2020-10-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasdet',
            name='total',
        ),
    ]
